CREATE TABLE IF NOT EXISTS user_(
	id VARCHAR(63) NOT NULL,
	username VARCHAR(31) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CONSTRAINT pk_user_id PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS user_pass_(
	user_id VARCHAR(63) NOT NULL,
	salt VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	CONSTRAINT pk_user_pass_id PRIMARY KEY (user_id),
	CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES user_(id)
);

